### ISSUE TITLE
好像少敲了一个空格 

### ISSUE THREAD

**Issue by xaotag** [baomihuahua/lolimeow#8]
![image](https://user-images.githubusercontent.com/40427877/78235906-deb95780-750b-11ea-96ed-b17df74ded9f.png)

**Comment by time-byte** [comment]
![image](https://user-images.githubusercontent.com/40427877/78236617-d281ca00-750c-11ea-8199-b68c44f57edd.png)
第二框显示不正常
![image](https://user-images.githubusercontent.com/40427877/78236802-17a5fc00-750d-11ea-9655-662088520ed8.png)
